const slides=[
['Sea Pines','Hilton Head Island','Pete Dye · Davis Love III · Arnold Palmer','Iconic south-island golf, beach, harbour and resort ownership.','https://paymegpt.com/objects/generated-images/1257/1787791827810-9e8d44a00d0d66ed.png'],
['Long Cove Club','Hilton Head Island','Pete Dye','Pure golf pedigree with marina access and a close residential culture.','https://paymegpt.com/objects/generated-images/1257/1787791838051-0da93af17a22dc33.png'],
['Wexford','Hilton Head Island','Arnold Palmer Design','Golf, a lock-controlled harbour and highly private residential living.','https://paymegpt.com/objects/generated-images/1257/1787791879645-3c44deb4192efa3a.png'],
['Belfair','Bluffton','Tom Fazio','Two championship courses and a sophisticated member sports campus.','https://paymegpt.com/objects/generated-images/1257/1787791848472-5a2ecc8223ae4f8e.png'],
['Berkeley Hall','Bluffton','Tom Fazio','Low-density Okatie River living built around a pure-golf philosophy.','https://paymegpt.com/objects/generated-images/1257/1787791838051-0da93af17a22dc33.png'],
['Colleton River Club','Bluffton','Pete Dye · Jack Nicklaus','Two major championship courses on a dramatic river peninsula.','https://paymegpt.com/objects/generated-images/1257/1787791827810-9e8d44a00d0d66ed.png']];
const directory=['Sea Pines|Hilton Head Island|4 courses · resort + private','Long Cove Club|Hilton Head Island|Pete Dye · private','Wexford|Hilton Head Island|Arnold Palmer · private','Palmetto Dunes|Hilton Head Island|Jones · Hills · Fazio','Leamington|Hilton Head Island|Arthur Hills','Shipyard|Hilton Head Island|27 holes','Port Royal Plantation|Hilton Head Island|Barony · Robber’s Row','Palmetto Hall|Hilton Head Island|Cupp · Hills','Indigo Run|Hilton Head Island|The Golf Club · Golden Bear','Hilton Head Plantation|Hilton Head Island|4 courses','Spanish Wells|Hilton Head Island|George Cobb · private','Belfair|Bluffton|Fazio East · West','Berkeley Hall|Bluffton|Fazio North · South','Colleton River Club|Bluffton|Dye · Nicklaus · par-3','Moss Creek|Bluffton|Devil’s Elbow North · South','Hampton Hall|Bluffton|Pete Dye','Palmetto Bluff|Bluffton|May River · Nicklaus','Rose Hill|Bluffton|Gene Hamm','The Crescent|Bluffton|Arnold Palmer Design','Pinecrest|Bluffton|Rocky Roquemore','Island West|Bluffton|Zoeller · Johnston','Eagle’s Pointe|Bluffton|Davis Love III','Oldfield|Greater Bluffton|Greg Norman','Sun City Hilton Head|Greater Bluffton|3 courses','Riverton Pointe|Greater Bluffton|Nicklaus Design','Hilton Head Lakes|Greater Bluffton|Tom Fazio','Callawassie Island|Greater Bluffton|27 holes · Tom Fazio'].map(x=>x.split('|'));
let order=[0,1,2,3,4,5],busy=false,timer;const root=document.getElementById('cards'),detail=document.getElementById('detail');slides.forEach((s,i)=>root.insertAdjacentHTML('beforeend',`<div class="card" id="c${i}" style="background-image:linear-gradient(90deg,rgba(5,16,11,.77),rgba(5,16,11,.06)),url('${s[4]}')"></div><div class="thumb-label" id="l${i}"><i></i><small>${s[1]}</small><strong>${s[0]}</strong></div>`));
function copy(i){detail.innerHTML=`<p>${slides[i][1]} · Golf real estate</p><h1>${slides[i][0]}</h1><h2>${slides[i][2]}</h2><span>${slides[i][3]}</span><div><a href="#communities">Explore community</a><a href="agents/">Meet an advisor</a></div>`}
function layout(){const w=innerWidth,h=document.querySelector('.motion').offsetHeight,cw=Math.min(205,w*.17),ch=Math.min(290,h*.36),gap=18,left=w-Math.min(760,w*.58),top=h-ch-92;order.forEach((id,p)=>{if(!p){gsap.set('#c'+id,{x:0,y:0,width:w,height:h,borderRadius:0,zIndex:10,scale:1});gsap.set('#l'+id,{opacity:0})}else{gsap.set('#c'+id,{x:left+(p-1)*(cw+gap),y:top,width:cw,height:ch,borderRadius:8,zIndex:30,scale:1});gsap.set('#l'+id,{x:left+(p-1)*(cw+gap),y:top+ch-72,opacity:1})}})}
function startTimer(){clearTimeout(timer);gsap.fromTo('#fill',{scaleX:0},{scaleX:1,duration:5.4,ease:'none'});timer=setTimeout(step,5400)}
function step(){if(busy)return;busy=true;clearTimeout(timer);const current=order[0],next=order[1],rest=order.slice(2),w=innerWidth,h=document.querySelector('.motion').offsetHeight;const targets=rest.map(id=>({id,x:gsap.getProperty('#c'+order[rest.indexOf(id)+1],'x')}));const tl=gsap.timeline({defaults:{ease:'sine.inOut'},onComplete:()=>{order.push(order.shift());copy(order[0]);layout();gsap.fromTo('.detail>*',{y:35,opacity:0},{y:0,opacity:1,duration:.55,stagger:.05});document.getElementById('num').textContent=String(slides.indexOf(slides[order[0]])+1).padStart(2,'0');busy=false;startTimer()}});tl.to('.detail>*',{y:35,opacity:0,duration:.3,stagger:.02},0).to('#c'+current,{scale:1.35,duration:.85},0).to('#l'+next,{opacity:0,y:'+=60',duration:.25},0).to('#c'+next,{x:0,y:0,width:w,height:h,borderRadius:0,zIndex:20,duration:.85},0);rest.forEach((id,i)=>tl.to('#c'+id,{x:gsap.getProperty('#c'+order[i+1],'x'),duration:.72},.08*i))}
copy(0);layout();addEventListener('resize',layout);document.getElementById('next').onclick=step;gsap.to('.cover',{xPercent:105,duration:1.05,delay:.2,ease:'sine.inOut'});gsap.from('.top',{y:-100,opacity:0,duration:.75,delay:.65});gsap.from('.detail>*',{x:-70,opacity:0,duration:.75,stagger:.08,delay:.72});gsap.from('.thumb-label',{x:'+=300',opacity:0,duration:.9,stagger:.08,delay:.65});startTimer();
document.getElementById('featuredGrid').innerHTML=slides.map((s,i)=>`<article class="club"><div class="club-img" style="background-image:url('${s[4]}')"><span>0${i+1}</span></div><small>${s[1]}</small><h3>${s[0]}</h3><p>${s[3]}</p></article>`).join('');document.getElementById('communityList').innerHTML=directory.map((d,i)=>`<article class="row"><span>${String(i+1).padStart(2,'0')}</span><div><h3>${d[0]}</h3><p>${d[1]}</p></div><div><p>${d[2]}</p></div><a href="agents/">↗</a></article>`).join('');